Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
str1="Disha Computer Instiute"
print(str1[0])
D
print(str1[3])
h
print(str1[0:3])
Dis
str1*2
'Disha Computer InstiuteDisha Computer Instiute'
str2="How are you"
str1+str2
'Disha Computer InstiuteHow are you'

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
Traceback (most recent call last):
  File "C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py", line 4, in <module>
    print(str1[0])
NameError: name 'str1' is not defined. Did you mean: 'str'?

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
D
C
p
s
m
a
u
u

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
Dis
sha Comp
iute
mputer Instiut
isha Comput
sha C

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
Dis
sha Comp
iute
mputer Instiut
isha Comput
sha C

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
Dis
sha Comp
iute
mputer Instiut
isha Comput
sha C

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====
Dis
sha Comp
iute
mputer Instiut
isha Comput
sha C

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====

====== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/Index.py =====

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[8, 65, 'Adarsh', 56.32]

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
8

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[8, 65, 'Adarsh', 56.32]

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[8, 65, 'Adarsh']

== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
<class 'list'>
>>> 
== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[34, 65, 'Adarsh', 56.32]
>>> 
== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[34, 65, 'Adarsh', 56.32]
(1, 8, 6)
>>> 
== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Disha Computer Instiute DehugaonIm Shital here for new joining student
[34, 65, 'Adarsh', 56.32]
Traceback (most recent call last):
  File "C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py", line 13, in <module>
    T1[1]=34
TypeError: 'tuple' object does not support item assignment
>>> 
== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
Traceback (most recent call last):
  File "C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py", line 17, in <module>
    print(t[1:]);
NameError: name 't' is not defined
>>> 
== RESTART: C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py ==
('python', 2, 1)
('shital',)
('shital', 'python', 2, 1)
('shital', 'python', 2, 1, 'shital', 'python', 2, 1)
('shital', 'python', 2, 1, 'shital', 'python', 2, 1, 'shital', 'python', 2, 1)
<class 'tuple'>
Traceback (most recent call last):
  File "C:/Users/telis/OneDrive/Desktop/PYTHON/Disha Comp/concatenate1.py", line 23, in <module>
    T1[2] = "hi";
TypeError: 'tuple' object does not support item assignment
